language: python

matrix:
  include:
    - language: generic
      os: osx
      env: PIP=pip2
    - python: "2.7"
      env: PIP=pip
    - python: "3.6"
      env: PIP=pip

before_install:
  - export DEKEN_BASE_URL=https://raw.githubusercontent.com/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}/developer
  - echo ${DEKEN_BASE_URL}

install:
  - mkdir -p ~/bin
  - mkdir -p tmp
  - cp developer/deken ~/bin/deken
  - chmod u+x ~/bin/deken
  - curl -fsSL -o tmp/deken-test.zip "https://puredata.info/Members/zmoelnig/tests/deken-test.zip"
  - (cd tmp; unzip deken-test.zip; rm deken-test.zip)

script:
  - ~/bin/deken upgrade
  - ~/bin/deken package -v000.dekenci tmp/deken-test
  - ~/bin/deken package --dekformat 0 -v000.dekenci tmp/deken-test
  - ~/bin/deken --version
  - ~/bin/deken --platform
  - ~/bin/deken find zexy
  - ~/bin/deken find --architecture "*" zexy

after_script:
  - ls -l
  - ls -l tmp/
