version: 1.0.{build}
configuration: Release
## not doing a shallow-clone, so we can run 'git describe' later
## (and anyhow, the repository is small)
#shallow_clone: true

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip

  - cd developer
  - pip install --no-compile -r requirements.txt
  - pip install pyinstaller

  - mkdir tmp
  - cd tmp
  - curl -fsSL -o deken-test.zip "http://puredata.info/Members/zmoelnig/tests/deken-test.zip"
  - 7z x deken-test.zip
  - rm deken-test.zip
  - cd ..

build_script:
  - for /f %%i in ('git describe --always') do set DEKEN_VERSION=%%i
  - pyinstaller deken.spec
  - set DEKEN_VERSION=
  - dist\deken -h
  - dist\deken --version
  - dist\deken --platform
  - dist\deken systeminfo
    #  - dist\deken package -v 000 tmp/deken-test
    #  - dist\deken package --dekformat 0 -v000.0 tmp/deken-test
  - dist\deken find zexy
  - dist\deken find --architecture "*" --depth 0 zexy

on_finish:
  - dir

artifacts:
  - path: developer\dist\deken.exe
    name: deken
