#!/bin/sh
if [ "x${1}" != "x" ]; then
  DEKEN_VERSION="$1"
fi
if [ "x${DEKEN_VERSION}" = "x" ]; then
  DEKEN_VERSION=$(git describe --alway)
fi
DEKEN_VERSION=${DEKEN_VERSION#v}
if [ -n "${DEKEN_VERSION}" ]; then
  sed -i '' -e "s|\(DEKEN_VERSION\)=\".*\"|\1=\"${DEKEN_VERSION}\"|g" developer/deken
  sed -i '' -e "s|\[\(::deken::versioncheck\) [^]]*\]|[\1 ${DEKEN_VERSION}]|g" deken-plugin.tcl
  sed -i '' -e "s|^\(version\):.*|\1: ${DEKEN_VERSION}|g" deken-test/README.deken.txt
fi

echo "${DEKEN_VERSION}"
