variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test
  - release
  - deploy
before_script:
  - date
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker info
  - docker images
after_script:
  - docker images
  - docker logout $CI_REGISTRY

build:
  stage: build
  tags:
    - docker-builder
  script:
    - ./.git-ci/git-version
    - docker build -t $CONTAINER_TEST_IMAGE developer
    - docker push $CONTAINER_TEST_IMAGE

release:
  stage: release
  tags:
    - docker-builder
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
