# iem-ci configuration for deken
stages:
  - build
  - test
  - release
  - deploy

variables:
 CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
 CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
 GIT_SUBMODULE_STRATEGY: normal


.build_script: &build_script
  script:
    - export DEKEN_VERSION=$(git describe --always)
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --user -r developer/requirements.txt
    - python3 -m pip install --user pyinstaller
    - for d in ~/Library/Python/*/bin; do test -d "${d}" && PATH=${PATH}:${d}; done || true
    - echo $PATH
    - (cd developer; pyinstaller deken.spec)

osx:
  tags:
    - osx
  stage: build
  before_script:
    - python3 --version || brew bundle --no-upgrade --file=.git-ci/requirements.brew
    - sudo chown -R $(whoami) /usr/local/ || echo "continuing without owning /usr/local"
  <<: *build_script
  after_script:
    - cp developer/dist/deken .
  artifacts:
    name: deken
    paths:
      - deken
    expire_in: 1 week

.windows:
  allow_failure: true
  tags:
    - windows
  variables:
    IEMCI_CONFIGURATIONS: python3
  stage: build
  <<: *build_script
  after_script:
    - cp developer/dist/deken.exe .
  artifacts:
    name: deken
    paths:
      - deken.exe
    expire_in: 1 week

# =====================================================================
# docker images
# =====================================================================

.docker:
  before_script:
    - date
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
    - docker images
  after_script:
    - docker images
    - docker logout $CI_REGISTRY
  tags:
    - docker-builder
  
docker-build:
  stage: build
  extends:
    - .docker
  script:
    - ./.git-ci/git-version
    - docker build -t $CONTAINER_TEST_IMAGE developer
    - docker push $CONTAINER_TEST_IMAGE

docker-release:
  stage: release
  extends:
    - .docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
